#spring.application.name=Journal App
#spring.data.mongodb.database=journaldb
#spring.data.mongodb.uri=mongodb+srv://suchitravm21_db_user:21012002_Atlas@cluster0.mohezup.mongodb.net/?appName=Cluster0
#spring.data.mongodb.auto-index-creation=true
#logging.level.org.springframework.security=DEBUG
#
#
#spring.security.user.name=user
#spring.security.user.password=password
#
#spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.http.converter.json=DEBUG
#logging.level.org.springframework.data.mongodb=DEBUG
#server.error.include-message=always
#server.error.include-stacktrace=always



spring:
  data:
    mongodb:
    uri: mongodb+srv://suchitravm21_db_user:21012002_Atlas@cluster0.mohezup.mongodb.net/?appName=Cluster0
    database: journaldb
    auto-index-creation: true
  spring:
    security:
      user:
        name: user
        password: password

sever:
  port: 8081
  servlet :
    context-path: /journal



